### ISSUE TITLE
`EspHttpClient` can't work with unknown-size data

### ISSUE THREAD

**Issue by maxwase** [esp-rs/esp-idf-svc#121]
If we will try to fetch some unknown-size data then this will not work.
```rust
let mut client = EspHttpClient::new(&EspHttpClientConfiguration {
    crt_bundle_attach: Some(esp_idf_sys::esp_crt_bundle_attach),
    ..Default::default()
})?;

let mut response = client.get(&url)?.submit()?;

let mut body = vec![
    0;
    response
        .content_len()
        .unwrap_or(0)
];

let (body, len) = io::read_max(response.reader(), &mut body)?;
info!("Read {} bytes", len);
// still some data left in reader
```

This happens due to the fact that `content_len` is not aware of chunked data, this is a possible fix:

```rust
fn content_len(&self) -> Option<usize> {
    let content_length = if unsafe { esp_http_client_is_chunked_response(self.client.raw) } {
        let mut len: i32 = 0;
        let res = unsafe { esp_http_client_get_chunk_length(self.client.raw, &mut len) };
        if res != 0 {
            0
        } else {
            len
        }
    } else {
        unsafe { esp_http_client_get_content_length(self.client.raw) }
    };
    if content_length >= 0 {
        Some(content_length as usize)
    } else {
        None
    }
}
```

But that will not work too because we still have more chunks left, so we need to somehow change `Read` implementation. We also probably want function like `read_all`.

**Comment by ivmarkov** [comment]
`content-length` is for informational purposes only. Regardless how the response is encoded (chunked or not) you are supposed to just call `read` on the response (response implements the `Read` trait) in a loip unti it reports 0 bytes read, which is EOF. Or use any of the adapter methods the can work with the `Read` trait.
