### ISSUE TITLE
Timer does not trigger

### ISSUE THREAD

**Issue by usbalbin** [esp-rs/esp-idf-svc#128]
The callback function does not seem to get called. There is no `Hi!` printed in the console.

```rust
fn main() {
    use esp_idf_sys as _;

    use std::time::Duration;
    use embedded_svc::timer::{TimerService, PeriodicTimer};
    use embedded_hal_0_2::prelude::_embedded_hal_blocking_delay_DelayMs;
    use esp_idf_hal::delay::FreeRtos;
    
    esp_idf_sys::link_patches();

    esp_idf_svc::timer::EspTimerService::new()
        .unwrap()
        .timer(|| println!("Hi!"))
        .unwrap()
        .every(Duration::from_secs(1))
        .unwrap();
    
    println!("Waiting for hi!");
    loop {
        FreeRtos.delay_ms(10000u16);
    }
}
```

same thing with `timer.after(...)`. `Waiting for hi!` is printed but nothing more, I have also tried toggling pins but nothing happens.

This is all with the untouched `sdkconfig.default` from the`cargo generate --git https://github.com/esp-rs/esp-idf-template cargo`

**Comment by ivmarkov** [comment]
You are supposed to keep around the returned timer so that it does not get dropped immediately.

**Comment by usbalbin** [comment]
Oh.. Thank you.
