### ISSUE TITLE
EspMqttClient::publish() with empty payload is causing a Guru Meditation Errors due to loading from 0x1

### ISSUE THREAD

**Issue by mike1703** [esp-rs/esp-idf-svc#146]
The function EspMqttClient::publish() accepts payload as `&[u8]` and uses it to feed the C function esp_mqtt_client_publish().
If an empty payload is to be sent ([] with length 0) the len is 0, so according to the documentation (and source code) the actual length is calculated from the payload string (with strlen()).

https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/protocols/mqtt.html#_CPPv423esp_mqtt_client_publish24esp_mqtt_client_handle_tPKcPKciii

> data – payload string (set to NULL, sending empty payload message)
> len – data length, if set to 0, length is calculated from payload string 

https://github.com/espressif/esp-mqtt/blob/master/mqtt_client.c#L1975-L1977

The issue here is, that in rust a pointer to the zero sized [] is actually 0x1, so the strlen() used in the c function is causing a load from 0x1...

https://github.com/esp-rs/esp-idf-svc/blob/6e8463074bbc0a4ab72b8dc484b3d1da646b5155/src/mqtt/client.rs#L453-L472

A fix could be to handle the payload.len() == 0 case to provide a NULL (ptr::null()) as payload.

**Comment by ivmarkov** [comment]
Great analysis - and I agree this is a bug! Would you mind contributing a small PR that fixes the issue?
