### ISSUE TITLE
Question: What is in a `StateMap`?

### ISSUE THREAD

**Issue by matthew-a-thomas** [esp-rs/esp-idf-svc#161]
https://esp-rs.github.io/esp-idf-svc/embedded_svc/httpd/type.StateMap.html

This type is returned from [`Request.session()`](https://esp-rs.github.io/esp-idf-svc/embedded_svc/httpd/struct.Request.html#method.session). What keys and values should one expect to find in there?

**Comment by ivmarkov** [comment]
I suggest to address these questions to the matrix chat instead.
