### ISSUE TITLE
MQTT Certificates

### ISSUE THREAD

**Issue by rherrmannr** [esp-rs/esp-idf-svc#162]
Hey, when do you plan to implement the certificates for MQTT?

https://github.com/esp-rs/esp-idf-svc/blob/master/src/mqtt/client.rs#L76
```
// TODO: Future

// pub cert_pem: &'a [u8],
// pub client_cert_pem: &'a [u8],
// pub client_key_pem: &'a [u8],
```

Do you have any suggested workaround to use them?

**Comment by ivmarkov** [comment]
Ideally, whoever needs them should open a PR with the changes. :) For example, you might volunteer, and then the whole community would benefit.

**Comment by rherrmannr** [comment]
I'm already trying to :P

**Comment by ivmarkov** [comment]
Fixed.
