### ISSUE TITLE
invalid dma channel, chip only support spi dma channel auto-alloc

### ISSUE THREAD

**Issue by teamplayer3** [esp-rs/esp-idf-svc#171]
When I want to initialize `EthDriver` with spi, I get this error

```
E (332) spi: spi_bus_initialize(762): invalid dma channel, chip only support spi dma channel auto-alloc
```

I think I located the error in the code: https://github.com/esp-rs/esp-idf-svc/blob/e20c313f574ee5eacf6ddbc6c2827e961f002d1b/src/eth.rs#L526

As a comment, it states `SPI_DMA_CH_AUTO` which is defined as `3` in [pi_common.h](https://github.com/espressif/esp-idf/blob/439a709c42/components/driver/include/driver/spi_common.h).

**Comment by ivmarkov** [comment]
If you feel like submitting another PR with `Dma::Auto` - no prob!
