### ISSUE TITLE
constantly rebooting at spi_bus_initialize (ethernet driver)

### ISSUE THREAD

**Issue by teamplayer3** [esp-rs/esp-idf-svc#173]
When I try to initialize the ethernet driver with spi, the board constantly reboots without throwing an error.

```
Board: esp32c3
esp-idf: v4.4
connected-board: w5500
Pins:
- int: spio2
- sclk: gpio15
- sdo: gpio16
- sdi: gpio17
- cs: gpio14
- reset gpio2
```

Tracked it down to:
https://github.com/esp-rs/esp-idf-svc/blob/336a8afe362f3835def7a12aea76969be2c8f419/src/eth.rs#L526

Can relate to this: https://www.esp32.com/viewtopic.php?t=17465
but this was an older idf version

Can somebody verify if it works on another esp32c3?

**Comment by ivmarkov** [comment]
A few things that could help:
1) Are you testing with latest `master` or with the published crate? We [got a fix earlier today]() - precisely on this line - but it is not yet in the `esp-idf-svc` version published on crates.io
2) Do you have a stack trace / memory dump from the crash that you can try to decode? Or an error message?

In any case, it would be great if you could try the `esp-idf-svc` version from `master` and let me know if it works for you now.

**Comment by teamplayer3** [comment]
Yes I use the master version. I detected the issue earlier this day while trying to make it work.

I don't get a esp error. This line gets called and the esp resets. I tracked it by inserting logs. No log after this function is called and no err() is returned.

**Comment by ivmarkov** [comment]
> Yes I use the master version. I detected the issue earlier this day while trying to make it work.
> 
> I don't get a esp error. This line gets called and the esp resets. I tracked it by inserting logs. No log after this function is called and no err() is returned.

Sorry. Losing track of who contributes what recently. :)

No idea what might have been causing this ATM.

**Comment by ivmarkov** [comment]
Which SPI device are you passing to the code?

**Comment by teamplayer3** [comment]
I initialize the driver as follows:

```rust
EthDriver::new_spi(
        peripherals.spi2,
        pins.gpio1,
        pins.gpio15,
        pins.gpio16,
        pins.gpio17,
        Some(pins.gpio14),
        Option::<Gpio2>::None,
        SpiEthChipset::W5500,
        20.MHz().into(),
        Some(&MAC_ADDR),
        None,
        sysloop.clone(),
    )
```

**Comment by ivmarkov** [comment]
I'm still at a loss as to what specifically is the problem, but in the meantime you have convinced me that exposing the `esp_idf_hal::spi::Dma` configuration option is a good idea. This way you can check if switching off DMA is helping, or if setting DMA with a smaller buffer size than 4096 would help.

I've pushed these changes to `master`. Can you try e.g. to switch off DMA, or to request smaller buffer size? Thanks!

**Comment by teamplayer3** [comment]
error[E0624]: associated function `max_transfer_size` is private
   --> /usr/local/cargo/git/checkouts/esp-idf-svc-a28457b0e32c6283/58e5837/src/eth.rs:516:34
    |
516 |             max_transfer_sz: dma.max_transfer_size(),
    |                                  ^^^^^^^^^^^^^^^^^ private associated function
    |

**Comment by ivmarkov** [comment]
> I initialize the driver as follows:
> 
> ```rust
> EthDriver::new_spi(
>         peripherals.spi2,
>         pins.gpio1,
>         pins.gpio15,
>         pins.gpio16,
>         pins.gpio17,
>         Some(pins.gpio14),
>         Option::<Gpio2>::None,
>         SpiEthChipset::W5500,
>         20.MHz().into(),
>         Some(&MAC_ADDR),
>         None,
>         sysloop.clone(),
>     )
> ```

Hmmmmm. Are you sure that **not** passing a reset pin is ok? For reference, my code, which was tested to work, although quite some time ago: https://github.com/ivmarkov/rust-esp32-std-demo/blob/main/src/main.rs#L243

I think the W5500 chipset does have a reset pin?

**Comment by ivmarkov** [comment]
> ```
> error[E0624]: associated function `max_transfer_size` is private
>    --> /usr/local/cargo/git/checkouts/esp-idf-svc-a28457b0e32c6283/58e5837/src/eth.rs:516:34
>     |
> 516 |             max_transfer_sz: dma.max_transfer_size(),
>     |                                  ^^^^^^^^^^^^^^^^^ private associated function
>     |
> ```

Yes. We need a new `esp-idf-hal` version. Publishing... Will ping you once ready; need to re-pull `esp-idf-svc` then.

**Comment by ivmarkov** [comment]
Can you pull `esp-idf-svc` and try again?

**Comment by ivmarkov** [comment]
And see my other comment for the reset pin...

**Comment by teamplayer3** [comment]
> > I initialize the driver as follows:
> > ```rust
> > EthDriver::new_spi(
> >         peripherals.spi2,
> >         pins.gpio1,
> >         pins.gpio15,
> >         pins.gpio16,
> >         pins.gpio17,
> >         Some(pins.gpio14),
> >         Option::<Gpio2>::None,
> >         SpiEthChipset::W5500,
> >         20.MHz().into(),
> >         Some(&MAC_ADDR),
> >         None,
> >         sysloop.clone(),
> >     )
> > ```
> 
> Hmmmmm. Are you sure that **not** passing a reset pin is ok? For reference, my code, which was tested to work, although quite some time ago: https://github.com/ivmarkov/rust-esp32-std-demo/blob/main/src/main.rs#L243
> 
> I think the W5500 chipset does have a reset pin?

Tested it with the reset pin set to gpio2 as well, same result.

Does the espidf some bus checks at init?

**Comment by ivmarkov** [comment]
The reset pin should of course be connected. What about dma being disabled?

**Comment by teamplayer3** [comment]
Checking my log again, the board panics before restarting

```
Saved PC:0x40380082
0x40380082 - _panic_handler
    at ??:??
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd6100,len:0x172c
load:0x403ce000,len:0x928
0x403ce000 - _coredump_iram_end
    at ??:??
load:0x403d0000,len:0x2ce0
0x403d0000 - _coredump_iram_end
    at ??:??
entry 0x403ce000
0x403ce000 - _coredump_iram_end
    at ??:??
```

Can I use this to investigate it further?

When I change dma to `disabled` a watchdog is fired after some time:
```
0x40380000 - _vector_table
    at ??:??
```

If I change it to `Dma::Auto(4096 / 2)` I get:
```
0x420348e0 - uart_hal_write_txfifo
    at /home/esp32dev/.espressif/esp-idf/release-v4.4/components/hal/uart_hal_iram.c:37
```
and
```
0x420348d4 - uart_ll_write_txfifo
    at /home/esp32dev/.espressif/esp-idf/release-v4.4/components/hal/esp32c3/include/hal/uart_ll.h:277
```
alternately.

**Comment by ivmarkov** [comment]
Can you output here the full log?

**Comment by teamplayer3** [comment]
I updated espflash, and now I don't get these logs any more (version 2.0.0-rc.1). Can I re-enable it?

```
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x8 (TG1WDT_SYS_RST),boot:0xd (SPI_FAST_FLASH_BOOT)
Saved PC:0x40380082
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5820,len:0x16ec
load:0x403cc710,len:0x95c
load:0x403ce710,len:0x2dc0
SHA-256 comparison failed:
Calculated: 25af9e3d109d88d02c90be5fb57af4df4234571b6f90ea288a6f8f2da8742ea7
Expected: 9fafed52ab0387e903bde368d0d6bfffe0dcc3d2f90dca069a4db891108c387c
Attempting to boot anyway...
entry 0x403cc710
I (53) boot: ESP-IDF v5.0-beta1-764-gdbcf640261 2nd stage bootloader
I (53) boot: compile time 11:30:26
I (54) boot: chip revision: V003
I (57) boot.esp32c3: SPI Speed      : 80MHz
I (62) boot.esp32c3: SPI Mode       : DIO
I (67) boot.esp32c3: SPI Flash Size : 4MB
W (71) boot.esp32c3: PRO CPU has been reset by WDT.
I (77) boot: Enabling RNG early entropy source...
I (82) boot: Partition Table:
I (86) boot: ## Label            Usage          Type ST Offset   Length
I (93) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (101) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (108) boot:  2 factory          factory app      00 00 00010000 003f0000
I (116) boot: End of partition table
I (120) boot_comm: chip revision: 3, min. application chip revision: 0
I (127) esp_image: segment 0: paddr=00010020 vaddr=3c080020 size=19ea8h (106152) map
I (153) esp_image: segment 1: paddr=00029ed0 vaddr=3fc8d800 size=01f70h (  8048) load
I (154) esp_image: segment 2: paddr=0002be48 vaddr=40380000 size=041d0h ( 16848) load
I (162) esp_image: segment 3: paddr=00030020 vaddr=42000020 size=76cd8h (486616) map
I (244) esp_image: segment 4: paddr=000a6d00 vaddr=403841d0 size=095e8h ( 38376) load
I (256) boot: Loaded app from partition at offset 0x10000
I (256) boot: Disabling RNG early entropy source...
I (267) cpu_start: Pro cpu up.
I (276) cpu_start: Pro cpu start user code
I (276) cpu_start: cpu freq: 160000000
I (276) cpu_start: Application information:
I (279) cpu_start: Project name:     libespidf
I (284) cpu_start: App version:      1
I (288) cpu_start: Compile time:     Nov 23 2022 12:50:11
I (294) cpu_start: ELF file SHA256:  0000000000000000...
I (300) cpu_start: ESP-IDF:          1f63dc7-dirty
I (306) heap_init: Initializing. RAM available for dynamic allocation:
I (313) heap_init: At 3FC92FB0 len 00049760 (293 KiB): DRAM
I (319) heap_init: At 3FCDC710 len 00002950 (10 KiB): STACK/DRAM
I (326) heap_init: At 50000020 len 00001FE0 (7 KiB): RTCRAM
I (333) spi_flash: detected chip: generic
I (337) spi_flash: flash io: dio
I (341) sleep: Configure to isolate all GPIO pins in sleep state
I (348) sleep: Enable automatic switching of GPIO sleep configuration
I (355) cpu_start: Starting scheduler.
I (360) system_api: Base MAC address is not set
I (360) system_api: read default base MAC address from EFUSE
I (370) esp32c3_w5500_example: 1
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x8 (TG1WDT_SYS_RST),boot:0xd (SPI_FAST_FLASH_BOOT)
Saved PC:0x40380080
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5820,len:0x16ec
load:0x403cc710,len:0x95c
load:0x403ce710,len:0x2dc0
SHA-256 comparison failed:
Calculated: 25af9e3d109d88d02c90be5fb57af4df4234571b6f90ea288a6f8f2da8742ea7
Expected: 9fafed52ab0387e903bde368d0d6bfffe0dcc3d2f90dca069a4db891108c387c
Attempting to boot anyway...
entry 0x403cc710
I (53) boot: ESP-IDF v5.0-beta1-764-gdbcf640261 2nd stage bootloader
I (53) boot: compile time 11:30:26
I (54) boot: chip revision: V003
I (57) boot.esp32c3: SPI Speed      : 80MHz
I (62) boot.esp32c3: SPI Mode       : DIO
I (67) boot.esp32c3: SPI Flash Size : 4MB
W (71) boot.esp32c3: PRO CPU has been reset by WDT.
I (77) boot: Enabling RNG early entropy source...
I (82) boot: Partition Table:
I (86) boot: ## Label            Usage          Type ST Offset   Length
I (93) boot:  0 nvs              WiFi data        01 02 00009000 00006000
I (101) boot:  1 phy_init         RF data          01 01 0000f000 00001000
I (108) boot:  2 factory          factory app      00 00 00010000 003f0000
I (116) boot: End of partition table
```

**Comment by ivmarkov** [comment]
This has nothing to do with espflash I think. 

The MCU resets so hard (I think) that you cannot even see the issues.

By the way, are you sure that you are properly powering the board? 
While - if there is not enough power - you should see "brownout" logs, I don't think it is guaranteed. 

For me it is strange that *just powering the SPI bus is leading to a reset*. I mean, the thing resets **before** the actual ETH SPI code even starts. Basically - and if my hypothesis is right - and if you correctly identified the problematic line as this one:
```
esp!(unsafe { spi_bus_initialize(P::device(), &bus_config, 3) })?; // SPI_DMA_CH_AUTO 
```

... this is not even eth specific. So a few things you could try:
- Can you put a log statement and a sleep for a few seconds AFTER this line? So that we can confirm/deny it breaks there exactly?
- Can you try to execute the code with the w5500 disconnected from power?
-

**Comment by teamplayer3** [comment]
Yes, I think I power the board properly. I have it connected to my pc via USB as all time.

inserted code
```
log::info!("before spi_bus_initialize");
esp!(unsafe { spi_bus_initialize(P::device(), &bus_config, dma.into()) })?;

unsafe { esp_idf_sys::vTaskDelay(500) }
log::info!("after spi_bus_initialize");
```
log:
```
I (294) cpu_start: ELF file SHA256:  0000000000000000...
I (300) cpu_start: ESP-IDF:          1f63dc7-dirty
I (306) heap_init: Initializing. RAM available for dynamic allocation:
I (313) heap_init: At 3FC92FB0 len 00049760 (293 KiB): DRAM
I (319) heap_init: At 3FCDC710 len 00002950 (10 KiB): STACK/DRAM
I (326) heap_init: At 50000020 len 00001FE0 (7 KiB): RTCRAM
I (333) spi_flash: detected chip: generic
I (337) spi_flash: flash io: dio
I (341) sleep: Configure to isolate all GPIO pins in sleep state
I (348) sleep: Enable automatic switching of GPIO sleep configuration
I (355) cpu_start: Starting scheduler.
I (360) system_api: Base MAC address is not set
I (360) system_api: read default base MAC address from EFUSE
I (370) esp32c3_w5500_example: 1
I (370) esp_idf_svc::eth: before spi_bus_initialize
ESP-ROM:esp32c3-api1-20210207
Build:Feb  7 2021
rst:0x8 (TG1WDT_SYS_RST),boot:0xd (SPI_FAST_FLASH_BOOT)
Saved PC:0x40380000
SPIWP:0xee
mode:DIO, clock div:1
load:0x3fcd5820,len:0x16ec
load:0x403cc710,len:0x95c
load:0x403ce710,len:0x2dc0
SHA-256 comparison failed:
Calculated: 25af9e3d109d88d02c90be5fb57af4df4234571b6f90ea288a6f8f2da8742ea7
Expected: 9fafed52ab0387e903bde368d0d6bfffe0dcc3d2f90dca069a4db891108c387c
Attempting to boot anyway...
entry 0x403cc710
```

**Comment by teamplayer3** [comment]
I created a pure `SpiDriver` and get the same behaviour. So I think I have to check the pins again or maybe another spi board.

While testing this I come up with the question, why does the EthDriver not depends on a pure SpiDriver / device.

**Comment by teamplayer3** [comment]
> I created a pure `SpiDriver` and get the same behaviour. So I think I have to check the pins again or maybe another spi board.
> 
> While testing this I come up with the question, why does the EthDriver not depends on a pure SpiDriver / device.

I testet the standard `SpiDriver` with another board and get the exact same behaviour. Tomorrow, I will ask a college to look over my pinouts to verify I didn't do anything wrong.

**Comment by Vollbrecht** [comment]
can you test the simple loopback spidriver example? i am curious that you got an TG1WDT_SYS_RST reset. nothing in the spi driver has anything to do with working on the Timer1 afaik. It just seems your cpu hangs and the WDT1 interupt is not reset back correctly. Are you using any other interupts / critical-sections that can lock the device up ?

**Comment by teamplayer3** [comment]
> can you test the simple loopback spidriver example? i am curious that you got an TG1WDT_SYS_RST reset. nothing in the spi driver has anything to do with working on the Timer1 afaik. It just seems your cpu hangs and the WDT1 interupt is not reset back correctly. Are you using any other interupts / critical-sections that can lock the device up ?

My program with the SpiDriver looks as follows and "driver" is never shown in the logs:
```
fn main() -> Result<()> {
    esp_idf_sys::link_patches();

    // Bind the log crate to the ESP Logging facilities
    esp_idf_svc::log::EspLogger::initialize_default();

    let peripherals = Peripherals::take().unwrap();
    let pins = peripherals.pins;

    let sysloop = EspSystemEventLoop::take()?;

    let driver = SpiDriver::new(
        peripherals.spi2,
        pins.gpio15,
        pins.gpio16,
        Some(pins.gpio17),
        Dma::Auto(4096),
    )?;

    log::info!("driver");

    let config_1 = config::Config::new().baudrate(20.MHz().into());
    let mut device_1 = SpiDeviceDriver::new(&driver, Some(pins.gpio14), &config_1)?;

    Ok(())
```

**Comment by Vollbrecht** [comment]
how does the behavior change when using Dma::Channel1 Dma::channel2 ? Just to make sure it is working when you use Dma::disabled right?

**Comment by teamplayer3** [comment]
If use the channels I get the error that only `Auto` is supported.

```
E (307) spi: spi_bus_initialize(762): invalid dma channel, chip only support spi dma channel auto-alloc
Error: ESP_ERR_INVALID_ARG
```

**Comment by ivmarkov** [comment]
> I created a pure `SpiDriver` and get the same behaviour. So I think I have to check the pins again or maybe another spi board.
> 
> While testing this I come up with the question, why does the EthDriver not depends on a pure SpiDriver / device.

That's a fair question actually. :) Before this release, `SpiDriver` was not a thing, as we did not have a notion of a "bus" driver. Only a "device" driver. Now that we have `SpiDriver` modeling the SPI bus (and `SpiDeviceDriver` modeling a concrete device on the bus), we can actually require - in eth - an `SpiDriver` instance.

**Comment by ivmarkov** [comment]
Having the `EthDriver` depending on `SpiDeviceDriver` was possible *before* ESP IDF 5, but not anymore. In ESP IDF 5, the underlying ESP IDF C code wants to create the "spi device" we are only in control / create the SPI bus / host.
I think they did it like that because they spin the SPI device itself and its transactions ion a separate thread/task or something. Or so I noticed.

**Comment by Vollbrecht** [comment]
ah i didn't see that you are using esp-idf 5. are you depending on it or can you try it with esp-idf 4-4 ?

**Comment by teamplayer3** [comment]
> ah i didn't see that you are using esp-idf 5. are you depending on it or can you try it with esp-idf 4-4 ?

I use esp-idf-4.4

**Comment by Vollbrecht** [comment]
`I (53) boot: ESP-IDF v5.0-beta1-764-gdbcf640261 2nd stage bootloader`

**Comment by ivmarkov** [comment]
> `I (53) boot: ESP-IDF v5.0-beta1-764-gdbcf640261 2nd stage bootloader`

Thats just the bootloader.

**Comment by Vollbrecht** [comment]
yeah but is it fine to mix and match here? just a hunch though

**Comment by teamplayer3** [comment]
> Having the `EthDriver` depending on `SpiDeviceDriver` was possible _before_ ESP IDF 5, but not anymore. In ESP IDF 5, the underlying ESP IDF C code wants to create the "spi device" we are only in control / create the SPI bus / host. I think they did it like that because they spin the SPI device itself and its transactions ion a separate thread/task or something. Or so I noticed.
> 
> So to summarize, we can have `EthDriver` depending on `SpiDriver`, but not really on `SpiDeviceDriver`.
> 
> It is another question whether the Eth device will behave properly if it is sharing the SPI bus with another SPI device. No idea.

So yes it could bepend on a SpiDriver.

I think the `fn init_spi_bus()`function in `eth.rs` is mostly the same as in `new_internal()` in `spi.rs`.
In `eth.rs` there is the addition of `gpio_install_isr_service(0)`.

**Comment by teamplayer3** [comment]
Can you check the spi_loopback on a esp32c3?

**Comment by Vollbrecht** [comment]
`I (267) cpu_start: ESP-IDF:          v4.4.1-dirty` did you made changes here /  can you test with v4.4.3 ?

**Comment by teamplayer3** [comment]
how can i use a tag as a version?

> `I (267) cpu_start: ESP-IDF: v4.4.1-dirty` did you made changes here / can you test with v4.4.3 ?

**Comment by teamplayer3** [comment]
> i just realized, you are using the internal gpio's that are also used on SPI1.

I use the once which are explicitly named on the dev kit as spi pins.

**Comment by teamplayer3** [comment]
> i just realized, you are using the internal gpio's that are also used on SPI1.

should I try other once. Which once?

**Comment by Vollbrecht** [comment]
yes please all pins but 12-17

**Comment by Vollbrecht** [comment]
what c3 module are you using?

**Comment by teamplayer3** [comment]
ESP-c3-32s-Kit

> what c3 module are you using?

**Comment by Vollbrecht** [comment]
yeah this pins should only be used to connect external_flash / psram afaik + SPI1 is per esp-idf docu not supported on esp32c3 master driver. so avoid this pins for everything else

**Comment by Vollbrecht** [comment]
please wright an angry mail to waveshare  :smile_cat:

**Comment by teamplayer3** [comment]
> yeah this pins should only be used to connect external_flash / psram afaik + SPI1 is per esp-idf docu not supported on esp32c3 master driver. so avoid this pins for everything else

So you are right. That's the error. Thanks for helping.

**Comment by Vollbrecht** [comment]
technically SPI2 has some native pins without going through the GPIO-MATRIX -> checkout the esp32c3 reference manual for it. Though it might matter only for real high speed latency sensitive things. Otherwise you can use any pin

**Comment by teamplayer3** [comment]
@ivmarkov I wanted to add that these esp32 crates are very nice work. And I'm looking forward to how they will develop.

**Comment by ivmarkov** [comment]
Shall we close this now? We can track moving `EthDriver` on top of `SpiDriver` as a separate effort. And we anyway need to confirm there that this would allow sharing the SPI bus with multiple devices, one of which is the eth device, or otherwise it is not worth it.
