### ISSUE TITLE
Change wifi client hostname

### ISSUE THREAD

**Issue by noahpnio** [esp-rs/esp-idf-svc#199]
I cannot find a function to change the wifi hostname of my esp32 (c3) in client mode. How can I proceed?

**Comment by taunusflieger** [comment]
I suggest to look into the ESP IDF documentation. It is important to understand that the Rust crates are sitting on top of IDF. Lots of concepts, but also settings are described there. 

To your question - have a look at https://docs.espressif.com/projects/esp-idf/en/release-v5.0/esp32/api-reference/kconfig.html?highlight=config_lwip_local_hostname#config-lwip-local-hostname

**Comment by ivmarkov** [comment]
There is no such thing as "hostname" in ESP IDF. What is there is a *suggestion* for a hostname that can be passed to your router *if* you configure your ESP with DHCP. Look at the `embedded-svc` `IpConfiguration` struct and specifically, the `hostname` optional parameter when DHCP is specified.
