### ISSUE TITLE
TLS Support in EspHttpServer?

### ISSUE THREAD

**Issue by brownjohnf** [esp-rs/esp-idf-svc#216]
I see that there's a feature `esp_idf_esp_https_server_enable` to enable serving over HTTPS; is there a reason this appears inaccessible to downstream consumers? I'd like to serve content over HTTPS, and it's not clear why it's restricted (or I'm being dumb about how to enable it).

**Comment by ivmarkov** [comment]
You need to enable HTTPS support for ESP IDF itself first, from within your`sdkconfig.defaults`. Check the ESP IDF documentation for the exact CONFIG_ name. Once you do that, all Rust HTTPS code will become magically enabled.
