### ISSUE TITLE
Regarding File System and WebSockets

### ISSUE THREAD

**Issue by akashlama1998-icloud** [esp-rs/esp-idf-svc#221]
Are there any examples for working with file system? Is there even anything available like SPIFFS or LittleFS or anything? And http server works great had no issues yet.. but are WebSockets supported right now or any examples on how I could implement it?

**Comment by ivmarkov** [comment]
All file systems that work with ESP IDF (spiffs and fatfs) do work with this crate. Please use the forum to ask for examples. I'll close this now, but if you have other questions/concerns - reopen.

**Comment by ivmarkov** [comment]
Websockets are supported, if you mean server-side (HTTP) support. Look at [this](https://github.com/ivmarkov/ruwm/blob/master/ruwm-esp32/src/services.rs#L349).
