### ISSUE TITLE
CONFIG_HTTPD_MAX_REQ_HDR_LEN

### ISSUE THREAD

**Issue by bbrietzke** [esp-rs/esp-idf-svc#225]
would like to be able to set CONFIG_HTTPD_MAX_REQ_HDR_LEN so that redirect headers and other header information can be used/set correctly for the web server component.

**Comment by ivmarkov** [comment]
Then set it? As everything else - in sdkconfig.defaults.

**Comment by bbrietzke** [comment]
thank you
