### ISSUE TITLE
EspHttpServer panic on handler error

### ISSUE THREAD

**Issue by dragazo** [esp-rs/esp-idf-svc#242]
I have an http(s) server running on an esp32-s3 board, and make frequent requests to it (~2Hz) for status info. Every once it a while (around every 4 minutes), I get a panic that resets the board. From further investigation, it appears to come from within the error handler for a request endpoint. Specifically, if a handler or the final send action returns `Err(_)`, the `EspHttpConnection::render_error` function is called, which renders a 500 error and message body. However, when this happens, the connection might not be in the request state, so the `self.assert_request()` line triggers an immediate panic and board reset.

I think the bigger issue here is that these functions return `Result` and yet still panic on certain failures. I don't know the specific rationale, but in this case, even returning `Err(ESP_FAIL)` would be better than just crashing because of one bad http request.

**Comment by ivmarkov** [comment]
The functions panic and (IMO) should panic, as these panics indicate a bug, rater than a normal behavior.
Specifically to your problem, `EspHttpConnection::render_error` should not try to render a 500 error and a message body if the user has already driven the connection into a response state, which is a bug.

**Comment by ivmarkov** [comment]
Hopefully, [this](https://github.com/esp-rs/esp-idf-svc/commit/9741d9a9270e69b9449d53b98ee05ab698d996ba) should take care of it. Please close this issue if it fixes the problem for you.
