### ISSUE TITLE
Rework README.md to contain better information for new users / simple how to get started 

### ISSUE THREAD

**Issue by Vollbrecht** [esp-rs/esp-idf-svc#254]

**Comment by ivmarkov** [comment]
Easiest is to just put there references to the `esp-idf-template` project, which already does have a how-to-get-started info, if by that you mean how to assemble a minimal project that depends on `esp-idf-svc`. We should probably put the same link in `esp-idf-hal` and `esp-idf-sys` readmes.

**Comment by ivmarkov** [comment]
We can also put mini.al info how to build the crate with examples (at least one more is coming next to the existing one). Ditto for `esp-idf-hal`.

**Comment by Vollbrecht** [comment]
yeah, i was thinking something along this line - maybe also add a link to the wokwi hello-world for a zero setup example. i will come up with something and make a PR

**Comment by ivmarkov** [comment]
Hopefully addressed now.
