### ISSUE TITLE
Consider releasing patch release with fix for `home_chan_dwell_time`

### ISSUE THREAD

**Issue by faern** [esp-rs/esp-idf-svc#277]
Building `esp-idf-svc` against ESP-IDF 4.4, 5.1 and master is broken due to https://github.com/espressif/esp-idf/issues/11921 / https://github.com/esp-rs/esp-idf-template/issues/139.

This has been fixed in commit https://github.com/esp-rs/esp-idf-svc/commit/42e60e8c3fcca670632b9653c790fd8efe475aac, but not yet released on crates.io. Could you please consider making a patch release? Currently nothing builds unless you replace your `esp-idf-svc` dependencies with the git `master` version.

I'm creating this issue to be able to track a release. But also because there are zero hits in the issue tracker for "home_chan_dwell_time". So this can be a landing for everyone who hits this error.

```
missing field `home_chan_dwell_time` in initializer of `esp_idf_sys::wifi_scan_config_t`
```

**Comment by MihaMarkic** [comment]
>  unless you replace your esp-idf-svc dependencies with the git master version

So, what exactly is the way to do it (consider myself as Rust newbie)? Get sources (including patch) from git and use them instead of crate?

**Comment by MihaMarkic** [comment]
Just in case anybody else was wondering, placing this in Cargo.toml seems to work:
```toml
[patch.crates-io]
esp-idf-svc = { git = "https://github.com/esp-rs/esp-idf-svc" }
```

**Comment by flyaruu** [comment]
Indeed, a patch release would be really welcome.

**Comment by ivmarkov** [comment]
`0.46.1` released.
