### ISSUE TITLE
How do I run bootloader_random_enable?

### ISSUE THREAD

**Issue by reinismu** [esp-rs/esp-idf-svc#280]
https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/random.html#_CPPv424bootloader_random_enablev

I need to enable it from rust

**Comment by ivmarkov** [comment]
https://github.com/esp-rs/esp-idf-sys/commit/0d13e8ed22ef6ec29c9e0922f155df9dfb2ba553
