### ISSUE TITLE
Problem using NVS (Esp32)

### ISSUE THREAD

**Issue by Ott-cop** [esp-rs/esp-idf-svc#284]
Goodnight!

I recently stumbled upon using Rust with Esp32, more specifically storing permanent content in memory so I can access it later. I saw that there were some related instructions on the Espressif website, despite being made for C code, I found the "same" libs for Rust and ended up making my code.

The problem is that I can't find examples of using NVS in Rust or any solution that I can base myself on and so on. Could you help me in some way?

PS: Sorry for the English mistakes.

**Comment by ivmarkov** [comment]
Did you look at the `examples` folder of crate `esp-idf-svc`? Also please join the esp-rs Matrix room listed in the crate README - best place to ask newbie questions.
