### ISSUE TITLE
Selecting network interfaces

### ISSUE THREAD

**Issue by torkleyy** [esp-rs/esp-idf-svc#286]
As far as I can see, there is currently no way to select which network interface should be used for services like:

* `EspHttpConnection`
* `EspHttpServer`

Consider that my ESP32 is connected via Ethernet, Wifi (Station) and Wifi (Access Point). I would like to be able to bind these services either to one of those interfaces or to all of them (the current implementation will just select one).

I can try adding this functionality if it is desired for this crate and somebody can give me some pointers.

But as far as I understand, it should already be possible to use any Rust http server, retrieve the IP from the desired interface and bind the server to it, correct?

**Comment by ivmarkov** [comment]
I don't think that the native ESP IDF HTTPD server exposes such a configuration option. It is hardcoded to [any](https://github.com/espressif/esp-idf/blob/master/components/esp_http_server/src/httpd_main.c#L364).
