### ISSUE TITLE
could not find `nvs` in the crate root

### ISSUE THREAD

**Issue by bss03arg** [esp-rs/esp-idf-svc#32]
HI

in esp-idf-svc, comma need to be add.
 #[cfg(esp32s3)]
    pin!(Gpio17:17, IO, RTC:17, ADC2:6, NODAC:0 NOTOUCH:0);

if I use this repo esp-idf-template with cmake.

my configuration of cargo.toml is:
...
[lib]
crate-type = ["staticlib"]

[profile.release]
opt-level = "s"

[profile.dev]
debug = true # Symbols are nice and they don't increase the size on Flash
opt-level = "z"

[dependencies]
log = "0.4"
esp-idf-sys = { version = "0.28.1", features = ["native"] }
esp-idf-svc = { version = "0.34.1" }
esp-idf-hal = "0.29.3"
embedded-svc = "0.15.4"

[build-dependencies]
embuild = "0.26"
anyhow = "1"

I got this error, if I add some wifi codes into rust lib, those codes are the same in example-std.

...
let netif_stack = Arc::new(EspNetifStack::new()?);
    let sys_loop_stack = Arc::new(EspSysLoopStack::new()?);
    let default_nvs = Arc::new(EspDefaultNvs::new()?);
    let mut wifi = wifi(
        netif_stack.clone(),
        sys_loop_stack.clone(),
        default_nvs.clone(),
    )?;
....
![image](https://user-images.githubusercontent.com/39295782/145159773-ae97869e-8adc-4511-8e84-fb0a2f601e99.png)

**Comment by ivmarkov** [comment]
> in esp-idf-svc, comma need to be add. #[cfg(esp32s3)] pin!(Gpio17:17, IO, RTC:17, ADC2:6, NODAC:0 NOTOUCH:0);
This is in `esp-idf-hal`, but anyway. I've added it, thanks. Will be available in the next `esp-idf-hal` minor release.

> I got this error, if I add some wifi codes into rust lib, those codes are the same in example-std.
> 
> ... let netif_stack = Arc::new(EspNetifStack::new()?); let sys_loop_stack = Arc::new(EspSysLoopStack::new()?); let default_nvs = Arc::new(EspDefaultNvs::new()?); let mut wifi = wifi( netif_stack.clone(), sys_loop_stack.clone(), default_nvs.clone(), )?; .... ![image](https://user-images.githubusercontent.com/39295782/145159773-ae97869e-8adc-4511-8e84-fb0a2f601e99.png)

The cmake-build (unlike the cargo one) does not bring-in all ESP-IDF components by default. Only a small fraction of ESP-IDF components are compiled by default, and hence the Rust wrappers for the others (including the 'nvs' one) are not compiled.

You need to add your component here: https://github.com/esp-rs/esp-idf-template/blob/master/cmake/components/rust-%7B%7Bproject-name%7D%7D/CMakeLists.txt#L3

I think the component you need to add is `nvs_flash`.
