### ISSUE TITLE
How to use with esp_modem component?

### ISSUE THREAD

**Issue by hongquan** [esp-rs/esp-idf-svc#339]
I want to connect to Internet via 4G, using SIMCOM A7672x module. How to use es-idf-svc with [esp_modem](https://components.espressif.com/components/espressif/esp_modem) component?

**Comment by ivmarkov** [comment]
Discussed in the Matrix room, let's close this.

**Comment by Vollbrecht** [comment]
you can add the matrix link to it if you click on share. Here is the [link](https://matrix.to/#/!LdaNPfUfvefOLewEIM:matrix.org/$Cq4kxb6NQqicrsymT5np80YJ1z5t6oYVQMBaa64zczc?via=matrix.org&via=tchncs.de&via=mozilla.org) in that time-frame
