### ISSUE TITLE
embassy timer impl is very inaccurate

### ISSUE THREAD

**Issue by t-moe** [esp-rs/esp-idf-svc#342]
Starting with a fresh (template-generated) project, and adding  
`embassy-time = { version = "0.1.5", features = ["generic-queue"] }` to my dependencies,
and with the following code:

```
use esp_idf_svc::hal::task::block_on;
use embassy_time::{Duration, Timer};

fn main() {
    esp_idf_svc::sys::link_patches();
    esp_idf_svc::log::EspLogger::initialize_default();

    block_on(async {
        for _ in 0..10 {
            log::info!("tick");
            Timer::after(Duration::from_secs(1)).await;
        }
    });
}


```

I get the output:

```
I (571) esp_idf_embassy_time: tick
I (2151) esp_idf_embassy_time: tick
I (5311) esp_idf_embassy_time: tick
I (11621) esp_idf_embassy_time: tick
I (24251) esp_idf_embassy_time: tick
I (49501) esp_idf_embassy_time: tick
I (100011) esp_idf_embassy_time: tick
```

which is very inaccurate.

The same code produces better results when using the `esp-idf-svc/embassy-time-isr-queue` feature and removing the `embassy-time/generic-queue` feature

**Comment by ivmarkov** [comment]
Should be fine now.

**Comment by bugadani** [comment]
@ivmarkov I hate to bother you with this, but next time please put at least one character into the commit message that isn't the issue number you're fixing. It's pretty annoying to find what has changed :D

**Comment by ivmarkov** [comment]
I will, but in the meantime... :P

[image: For_Daniel.png]
