### ISSUE TITLE
Compilation error, dependency issue: `embedded-svc` does not have feature `asyncify`

### ISSUE THREAD

**Issue by BRA1L0R** [esp-rs/esp-idf-svc#345]
Trying to compile `esp-idf-svc` from master branch returns this error. `embedded-svc` version 0.26.4 does not in fact have feature `asyncify`.

Somebody else also encountered this problem:

```
error: failed to select a version for `embedded-svc`.
    ... required by package `esp-idf-svc v0.47.3 (https://github.com/esp-rs/esp-idf-svc#0cc687be)`
versions that meet the requirements `^0.26.4` (locked to 0.26.4) are: 0.26.4
the package `esp-idf-svc` depends on `embedded-svc`, with features: `asyncify` but `embedded-svc` does not have these features.
```

_Originally posted by @OrganomagnesiumHalide in https://github.com/esp-rs/esp-idf-svc/issues/344#issuecomment-1891080970_

**Comment by ivmarkov** [comment]
You need to currently patch the dependencies of `esp-idf-svc` in your binary crate to also be pulled from git, as follows: https://github.com/esp-rs/esp-idf-svc/blob/master/Cargo.toml#L19

**Comment by ryankopf** [comment]
> You need to currently patch the dependencies of `esp-idf-svc` in your binary crate to also be pulled from git, as follows: https://github.com/esp-rs/esp-idf-svc/blob/master/Cargo.toml#L19

This comment is terribly misleading, because it does not link to a static version of Cargo.toml, and Cargo.toml has changed several times since your comment. Further, the changes shown don't work now that the git versions have moved on.

The whole point of version numbering is so that issues like this don't happen. There should NEVER be patches that require tracing several github commits to find in the wild. This issue should have been fixed and a minor version released, instead you guys chose to wait until 0.48, which contains breaking changes. This is not adequate.

**Comment by Vollbrecht** [comment]
It is not misleading, as the crates embedded-svc and esp-idf-svc needs to be kept in sync. The original suggestion was to upgrade to a then "master" version to git, in that moment in time. That also would include to have a then unreleased embedded-svc version.

a) Unreleased git masters doesn't have to do with anything about any "whole point of version numbers". 
b) Later we released a new version providing a fix but we didn't backport ( end of story). It might not be optimal but this is just a community driven freetime project. We do things within bounds of that here. 
c) At that time there were also other crates that introduced breaking changes ( heapless) that broke our public api. While not optimal nobody claims here that we are at a fully stable 1.0 with all there is to it. We acted and done the right think and upgraded with a breaking change. 
d) You are free to have your negative opinion here, i have no problem with it, but it doesn't fix anything and it doesn't bring anything useful to the table.

**Comment by ryankopf** [comment]
I apologize I meant misleading in that it literally "leads" to the wrong place, it does not lead to the specific line number the commenter intended.

It was meant to link to https://github.com/esp-rs/esp-idf-svc/blob/0cc687beb75086c0d2610e58182cb78dbd87044c/Cargo.toml#L19

Which makes it more clear that the issue involves:
```
[patch.crates-io]
embedded-svc = { git = "https://github.com/esp-rs/embedded-svc" }
esp-idf-hal = { git = "https://github.com/esp-rs/esp-idf-hal" }
esp-idf-sys = { git = "https://github.com/esp-rs/esp-idf-sys" }
```

And not:
```
[features]
default = ["std", "binstart"]
```
Which is where https://github.com/esp-rs/esp-idf-svc/blob/master/Cargo.toml#L19 links to
