### ISSUE TITLE
Is there a function similiar to esp_wifi_set_max_tx_power?

### ISSUE THREAD

**Issue by weiying-chen** [esp-rs/esp-idf-svc#360]
I have a similar problem as [this](https://github.com/tzapu/WiFiManager/issues/1422#issuecomment-1148828543) one. Does esp-idf-svc have a similar function as [esp-wifi](https://github.com/esp-rs/esp-wifi/)'s `esp_wifi_set_max_tx_power`?

**Comment by ivmarkov** [comment]
@weiying-chen the [matrix chat](https://matrix.to/#/#esp-rs:matrix.org) is a better place to ask these questions. You have opened 3 issues (this one, plus #359 + https://github.com/esp-rs/embedded-svc/issues/73 for a single problem that you are having. Which might still be a hardware problem.

With that said, `esp_wifi_set_max_tx_power` should be available as `unsafe` function in `esp-idf-sys` (or `esp_idf_svc::sys`, which is the same; you should be able to call it on the raw Wifi "handle", i.e. `wifi.driver().handle()`.

**Comment by weiying-chen** [comment]
@ivmarkov Got it. I'll try the matrix chat next time. Thanks for all the help!

**Comment by ivmarkov** [comment]
I still strongly suggest to try powering your board with a more powerful supply as a first step.

**Comment by weiying-chen** [comment]
@ivmarkov Yes, I'll follow your advice. I'll buy a USB hub with its own power supply. Then connect my mini PC and ESP32-C3 to it. Note: I need my mini PC and ESP32-C3 to be connected so I can debug with ESPMonitor.

**Comment by ivmarkov** [comment]
You can just use a USB power supply from a phone and connect it to the board. You won't get logs this way of course, but you can try pinging the IP of the board from your PC and see if the ping succeeds and stays stable. This way the power supply hypothesis can be confirmed / denied.

**Comment by weiying-chen** [comment]
@ivmarkov Ah, that's a good idea. But how do I get the IP of the board?

**Comment by ivmarkov** [comment]
Look at the DHCP leases of your router, in its WEB-UI.

**Comment by weiying-chen** [comment]
@ivmarkov Okay, I'll try that. Thanks a lot for the help.
