### ISSUE TITLE
WPS regression: Option::unwrap on event payload

### ISSUE THREAD

**Issue by torkleyy** [esp-rs/esp-idf-svc#377]
WPS no longer works in the latest release, it regressed in commit 29ce820f5012d70c5853c0c646efd7664658cd44

Line 1901 in that commit is problematic, as it assumes an event payload is present in any case.

In case there is just a single WPS config, the event payload will be empty and instead the wifi config is updated by the driver (very curious behavior in my opinion, but that's why we had the check in there). Thus, it will panic due to the unwrap.

**Comment by Vollbrecht** [comment]
thanks for reporting, can you try to create a PR fixing it?

**Comment by torkleyy** [comment]
Yes. Maybe we can merge my open PR https://github.com/esp-rs/esp-idf-svc/pull/368 in the meantime so I can easily test it within my application :D

**Comment by shekohex** [comment]
Hey, I did hit this issue today, any update on this?

**Comment by Vollbrecht** [comment]
#379 was merged
