### ISSUE TITLE
HTTP headers wrongly treated as case-sensitive by client

### ISSUE THREAD

**Issue by AlyoshaVasilieva** [esp-rs/esp-idf-svc#39]
EspHttpResponse defines headers as `BTreeMap<String, String>`: https://github.com/esp-rs/esp-idf-svc/blob/a39c1199b1468d6b581d457cdc752bdf5a38ed1d/src/http/client.rs#L314-L317

If a server sends `Content-Type: something`, then `resp.content_type()` returns `None` because [embedded_svc asks for `content-type`](https://github.com/esp-rs/embedded-svc/blob/47c21851fb47141629057ceb2f834c4139eb666e/src/http.rs#L59-L61) and `EspHttpResponse` does a case-sensitive search: https://github.com/esp-rs/esp-idf-svc/blob/a39c1199b1468d6b581d457cdc752bdf5a38ed1d/src/http/client.rs#L337-L339

I *think* the fix is replacing the `String` key with something like [`Uncased`](https://docs.rs/uncased/0.9.6/uncased/struct.Uncased.html)

**Comment by ivmarkov** [comment]
`Uncased` seems to cover our use case perfectly. Are you up for a PR?

**Comment by AlyoshaVasilieva** [comment]
I'll try to work on it within the next day or two

**Comment by sehraf** [comment]
What is the advantage of `uncased` over something simple like `to_lowercase()`?

**Comment by AlyoshaVasilieva** [comment]
Uncased doesn't require any additional allocations or modification of strings
