### ISSUE TITLE
Feature Request: Async HTTP and WebSocket clients

### ISSUE THREAD

**Issue by JadKHaddad** [esp-rs/esp-idf-svc#392]
Hello, It would be very helpful to add support for async HTTP and WebSocket clients as I've spent the last week trying to make async HTTP requests with TLS support work, attempting various libraries such as reqwest, reqwless, and embassy net, but unfortunately, nothing worked.

**Comment by ivmarkov** [comment]
The HTTP clients and esp. the WS client in ESP IDF are not really async, and would be difficult to make them behave like one. You are better off trying some of the pure Rust async HTTP and WS clients in top of ESP IDF's `AsyncEspTls` async TLS client. Like edge-http and edge-ws.
