### ISSUE TITLE
Only a few post requests are sent before program panics 

### ISSUE THREAD

**Issue by weiying-chen** [esp-rs/esp-idf-svc#399]
I'm sending post requests every 5 seconds inside a loop that will break when the iterations reach 10:

```
let mut iterations = 0;

loop {
    if scale.is_ready() {
        log::info!("Iteration number {}", iterations);
        
        // logic to set payload
     
        post_request(&mut client, payload_bytes)?;

        log::info!("Post request sent!");
    }

    FreeRtos::delay_ms(5000u32);

    iterations += 1;

    if iterations >= 10 {
        break;
    }
}
```

This is the `post_request` function:

```
fn post_request(client: &mut HttpClient<EspHttpConnection>, payload: &[u8]) -> anyhow::Result<()> {
    // set the key, url, and headers 

    let mut request = client.post(supabase_url, &headers)?;

    request.write_all(payload)?;
    request.flush()?;
    info!("-> POST {}", supabase_url);

    match request.submit() {
        Ok(response) => {
            let status = response.status();
            info!("<- HTTP Status: {}", status);
        }
        Err(e) => {
            info!("Error sending POST request: {:?}", e);
        }
    }

    Ok(())
}
```

The first POST requests will be sent. But then some warning and errors will show up and the program will panic and exit:

```
I (21162) rust_esp32c3_hx711: Iteration: 1
I (21502) esp-x509-crt-bundle: Certificate validated
I (22222) rust_esp32c3_hx711: -> POST https://pratqgdulutgohggfwfo.supabase.co/rest/v1/messages
I (22812) rust_esp32c3_hx711: <- HTTP Status: 201
I (22812) rust_esp32c3_hx711: Post request sent!
I (27812) rust_esp32c3_hx711: Iteration: 2
I (33152) rust_esp32c3_hx711: -> POST https://pratqgdulutgohggfwfo.supabase.co/rest/v1/messages
W (38472) HTTP_CLIENT: Connection timed out before data was ready!
I (38472) rust_esp32c3_hx711: Error sending POST request: EspIOError(EspError(-28679))
I (38472) rust_esp32c3_hx711: Post request sent!
I (43482) rust_esp32c3_hx711: Iteration: 3
thread 'main' panicked at /home/weiying-chen/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-idf-svc-0.48.1/src/http/client.rs:477:13:
connection is not in initial phase
````

What could be the issue here?

Notes: 
- It's getting stuck here: `match request.submit()`. And producing the timeout.
- I [tested](https://gist.github.com/weiying-chen/af32ce18a2848ca3df8f763c83337cda) running the same loop but without `esp-idf-svc`. The loop finishes successfully and all the post requests are sent.

**Comment by weiying-chen** [comment]
I've made two discoveries:

1. The same issue happens with a GET request: `get_request(&mut client)?;`
2. To fix the issue you have to create a new HTTP client after the timeout `*client = HttpClient::wrap(EspHttpConnection::new(&config)?);` 

But I still don't know what's causing the timeout.

**Comment by weiying-chen** [comment]
I made a discovery. The timeout happens when you send a requests (more than one) to an HTTPS server:

    let url = "https://httpbin.org/get";

The timeout won't happen if you send requests to an HTTP server:

     let url = "http://ifconfig.net/";

**Comment by weiying-chen** [comment]
I finally found the solution ... I had to drain the remaining response bytes:

```
 // Drain the remaining response bytes
 while response.read(&mut buf)? > 0 {}
```

**Comment by ivmarkov** [comment]
Yes, we don't auto-drain by default, and I'm not sure that's actually possible. If you find a way to auto-drain and open a PR, I think we can accept it.

**Comment by weiying-chen** [comment]
Okay, I'll open a PR if I find a way.
