### ISSUE TITLE
Non-static callbacks: What is "service"?

### ISSUE THREAD

**Issue by owenthewizard** [esp-rs/esp-idf-svc#400]
https://docs.esp-rs.org/esp-idf-svc/esp_idf_svc/wifi/struct.WifiDriver.html#method.set_nonstatic_callbacks
> HOWEVER: care should be taken NOT to call core::mem::forget() on the service, as that would immediately lead to an UB (crash). Also note that forgetting the service might happen with Rc and Arc when circular references are introduced: https://github.com/rust-lang/rust/issues/24456

What is the "service" here, the WifiDriver?

**Comment by Vollbrecht** [comment]
In general if you have questions please use the matrix channel linked in the README, so issues can be used for concrete problems
