### ISSUE TITLE
How to get access point IP address?

### ISSUE THREAD

**Issue by matthew-a-thomas** [esp-rs/esp-idf-svc#48]
Is it possible to get the IP address that ESP chose to give itself while in AP mode? Or will it always be the subnet's gateway IP address as given in `embedded_svc::ipv4::RouterConfiguration.subnet`?

Sorry if this is a dumb question. I'm learning the ropes and haven't even fired up my ESP32C3 as an access point yet. I'm just trying to make sense of the APIs.

**Comment by ivmarkov** [comment]
> Is it possible to get the IP address that ESP chose to give itself while in AP mode? Or will it always be the subnet's gateway IP address as given in `embedded_svc::ipv4::RouterConfiguration.subnet`?
> 

It will of course always be the subnet's gateway IP address. In AP mode, the ESP _is_ the gateway.
Just have in mind that if you do simultaneous AP+STA (as the demo does) then the ESP will have two IP addresses:
* The AP gateway address
* A DHCP address from your wifi network

... and will route traffic between the two. The AP traffic will be NAT-ed behind the AP gateway IP however (which is of course inconvenient a bit).
