### ISSUE TITLE
Cannot Change Wifi Connect Timeout

### ISSUE THREAD

**Issue by smallbraingames** [esp-rs/esp-idf-svc#509]
When connecting to wifi, a timeout of 15 seconds is hard coded here (https://github.com/esp-rs/esp-idf-svc/blob/7cf3a9ac4a43c8eba6ead60321e53019a9e3564b/src/wifi.rs#L2422C1-L2431C1). 

I have a use case where I want to give users feedback faster than this. Is there a reason why this timeout is so long? Could it be made configurable?

**Comment by ivmarkov** [comment]
If you notice the implementation of this  method is only using public API. Therefore, if you want to have a `connect` with a custom timeout, you can simply copy-paste the three lines of code in your own code and then adjust the timeout.
