### ISSUE TITLE
Unable to create websocket client

### ISSUE THREAD

**Issue by milewski** [esp-rs/esp-idf-svc#514]
Adding `CONFIG_HTTPD_WS_SUPPORT=y` to `sdkconfig.defaults` does not enable enable the WS features... 

https://github.com/esp-rs/esp-idf-svc/blob/cca1a609fefe11e54dce0cbbecd52e69b493ba59/src/ws.rs#L13-L22

Manually passing the args via rustflags passes the `cfg()` check:

```
rustflags = [
    "--cfg", "espidf_time64",
    "--cfg", "config_httpd_ws_support",
    "--cfg", "esp_idf_comp_espressif__esp_websocket_client_enabled",
    "--cfg", "esp_idf_comp_esp_websocket_client_enabled",
    "--cfg", "esp_idf_comp_tcp_transport_enabled",
    "--cfg", "esp_idf_comp_esp_tls_enabled",
    "--cfg", "esp_idf_ws_transport",
]
```

However rust complains about some missing functions... after further investigation I found out they were [removed from IDF](https://docs.espressif.com/projects/esp-idf/en/v5.2.3/esp32s3/migration-guides/release-5.x/5.0/removed-components.html#removed-or-deprecated-components) and moved to https://components.espressif.com/components/espressif/esp_websocket_client

**Comment by ivmarkov** [comment]
What you described had happened ages ago not only for websocket but for the mdns client - they are now esp idf remote components fetchable with the esp idf component manager.

Just add the websocket component to your crate and then re-enable the config as you tried initially.

Never cheat by passing "manually" configs to rustc via `--cfg`.
