### ISSUE TITLE
Accessing all gpio pins? 

### ISSUE THREAD

**Issue by chuckberrypi** [esp-rs/esp-idf-svc#516]
Sorry if this isn't an appropriate github issue, but I'm wondering why the `esp-idf-svc::hal::gpio` only has types for gpio pins 1 through 21. My board has up to pin 38, and I don't seem to have any way of accessing them through this library. Is that correct? Is there another way I can use all the pins on my board? Thanks!

**Comment by Vollbrecht** [comment]
if you are looking at the docs page it is generated against the esp32c3. If you are using another chip you get the correct gpio pins generatet for your chip. All capability definitions for every chip variant can be found in [esp-idf-ha](https://github.com/esp-rs/esp-idf-hal/blob/master/src/gpio.rs#L1619)l
