### ISSUE TITLE
Shouldn't EspNetifDriver be `pub` ?

### ISSUE THREAD

**Issue by Luctins** [esp-rs/esp-idf-svc#524]
Shouldn't this line be `pub mod ...`? 
https://github.com/esp-rs/esp-idf-svc/blob/3f4a2c0ec893c5acaeb2cb4d8af320ab07e7928c/src/netif.rs#L960

I'm investigating how to use PPP over serial and wanted to use this, but it is not public outside the crate. 
Is the example code in the comment here: https://github.com/esp-rs/esp-idf-svc/blob/3f4a2c0ec893c5acaeb2cb4d8af320ab07e7928c/src/netif.rs#L1005-L1022
still valid?

**Comment by ivmarkov** [comment]
[No it does not have to](https://github.com/esp-rs/esp-idf-svc/blob/3f4a2c0ec893c5acaeb2cb4d8af320ab07e7928c/src/netif.rs#L26).

To use PPP, you need to enable PPP support in your `sdkconfig.defaults`, with the relevant CONF setting. Google for "esp idf ppp enable sdkconfig"

**Comment by ivmarkov** [comment]
https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/kconfig.html#config-lwip-ppp-support

**Comment by ivmarkov** [comment]
Oh. And you need `feature = "experimental"` on the `esp-idf-svc` dependency.

**Comment by Luctins** [comment]
Oh! I really didn't saw that that `use driver::*` 🤦🏻 sorry and thanks for the help.
Also, why is this feature gated on `experimental` ?

**Comment by ivmarkov** [comment]
Closing - still - let me know if you have troubles.
