### ISSUE TITLE
How to set http header size please.

### ISSUE THREAD

**Issue by buhe** [esp-rs/esp-idf-svc#57]
```
E (21685) HTTP_HEADER: Buffer length is small to fit all the headers
```

Maybe my header is too big.

**Comment by MabezDev** [comment]
Please see the `CONFIG_HTTPD_MAX_REQ_HDR_LEN` from https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/kconfig.html#http-server. Configure your custom value in your projects sdkconfig file.

**Comment by buhe** [comment]
thanks
