### ISSUE TITLE
using wifi with async/await (AsyncEventBus)

### ISSUE THREAD

**Issue by teamplayer3** [esp-rs/esp-idf-svc#80]
I try to use the wifi `wait_status_with_timeout()` function in an `async` task. As I understand, the `experimental` feature `as_async()` can be used to archive this.

So, to get an event change asynchronously, I use it like so:

```rust
wifi.set_configuration(...);

{
    let mut wifi = wifi.as_async();
    let mut sub = wifi.subscribe().unwrap();
    sub.recv().await?;
}

let status = wifi.get_status();
```

But, after running this, it waits forever at `sub.recv().await?;`.

Do I have to use it differently, or do I have to configure something to use it? Are there any plans to provide `wait_status_with_timeout()` as an async version?

**Comment by ivmarkov** [comment]
`sub.recv().await?` will indicate you that the `Status` instance of the `Wifi` trait had changed, but not necessarily that the Wifi is connected. You still need to call `wifi.get_status()` afterwards to inspect if the Wifi is connected, or else await again.

You can also use the above to cover other use cases as well, like when the Wifi gets disconnected for example.

What executor are you using to spin the above await btw?

**Comment by ivmarkov** [comment]
Oh and by the way:
*  in between `wifi.set_configuration` and your call to `subscribe`, the status might had changed already, so if you just unconditionally `await` it could be forever, yes
* Moreover, once you call `subscribe`, you **have to** read messages in a loop from the subscription, or else you'll block the whole system event loop

Perhaps my problem is that I'm not sure what you are actually trying to achieve in general, with the async call?

**Comment by ivmarkov** [comment]
Closing - feel free to reopen with additional details.

**Comment by teamplayer3** [comment]
In general, I want to wait for status change but with not blocking the whole thread like I would do with `wait_status_with_timeout()`.

As an executer I use smol as it is in the example [esp32-demo-app](https://github.com/ivmarkov/rust-esp32-std-demo).

**Comment by ivmarkov** [comment]
But if you go async you have to go async for everything or at least for all the workload you schedule on that particular thread. Can you share a bigger sample of what you are trying to accomolish?

**Comment by teamplayer3** [comment]
I want to do nearly the same as described in #73. I try to have all my functionality in one thread. This means I want to handle the wifi configuration, I host a rest interface and serve a small configuration web page.

For the hosting part, I use crates routerify and hyper. This works well with async. Now I need the async behavior for the wifi handling on the esp. Can you provide me with some info on what's the status of this crate using async. I need for example the `scan`, the `wait_on_status_change` as I said and the `configuration` methods. 

Unfortunate, the functionality I want to have is implemented in a larger project in a private repo. But I plan to write a small test, for the async behavior of the wifi.

Thanks for your help.
