### ISSUE TITLE
Logger panics if output contains null bytes

### ISSUE THREAD

**Issue by tcbennun** [esp-rs/esp-idf-svc#91]
The offending line:
https://github.com/esp-rs/esp-idf-svc/blob/e1e0df191bd0929f68c5e63b217395abc7941a5b/src/log.rs#L135

I don't believe it should be up to the caller to ensure the log record doesn't contain null bytes - this occurs safely in Rust. I think we should post-process `output` to remove null bytes (they'd be invisible anyway) before conversion to `CString`.

Thoughts?

**Comment by tcbennun** [comment]
Fair enough :)

#92

**Comment by ivmarkov** [comment]
Closed via #92
